export const hebrew = {
    appName: 'סידור משמרת',
    shift: "משמרת",
    sunday: "ראשון",
    monday: "שני",
    tuesday: "שלישי",
    wednesday: "רביעי",
    thursday: "חמישי",
    friday: "שישי",
    saturday: "שבת",
    save: "שמור",
    cancel: "ביטול",
    edit: "עריכה",
    delete: "מחיקה",
    clear: "ניקוי",
    clearAll: "נקה הכל",
    add: "הוספה",
    total: "סהכ",
    hours: "שעות",
    minutes: "דקות",
    seconds: "שניות",
    time: "זמן",
    name: "שם",
    email: "אימייל",
    password: "סיסמא",
    login: "התחברות",
    register: "הרשמה",
    logout: "התנתקות",
    welcome: "ברוך הבא",
    home: "בית",
    profile: "פרופיל",
    settings: "הגדרות",
    employees: 'עובדים',
    date: "תאריך"
    
    
}